### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [xiph/flac#111]
I think that it would be good to flush away all already committed changes and make new release with updated code base :)

**Comment by Barough** [comment]
I totally agree with you. All these years of waiting for a new release is just ridicules.

**Comment by erikd** [comment]
@Barough "All these years"? Really? The last release was 2.5 years ago. Let me remind you that before I became the maintainer, FLAC has no new release for 5 or 6 years.

What has gone into the code base since then that you are so desperate for that using a git checkout for is inadequate?

**Comment by kloczek** [comment]
Please do not focus on personal aspects of this conversation.
It really doesn't matter who done what and when.

Can you tell a bit about possible next release? :)
Do you have some plans about fixing some other unknown issues which stops make next release?

**Comment by erikd** [comment]
I do not have any outstanding work that is delaying a release.

I also do not do releases simply because its been a certain amount of time since the last release. However, if someone can say feature X or bug Y was fixed in git since the last release and it would be nice to have a release that includes that, then yes, a release is warranted.

**Comment by kloczek** [comment]
You are right that nothing critical have been fixed in already committed changes however few minor fixes have been committed,
IMO it would bi good to push out all of those changes as new updated release to provide updated code base.
Only this and nothing more.

**Comment by petterreinholdtsen** [comment]
As one of the people involved in Debian, I would like to mention that it
would be great to have a new release of flac released with the six
patches carried by Debian included,
<URL: https://sources.debian.org/src/flac/1.3.2-3/debian/patches/ >,
to make sure the package is in sync between Linux distributions.

<URL: https://tracker.debian.org/pkg/flac >

-- 
Happy hacking
Petter Reinholdtsen

**Comment by erikd** [comment]
@petterreinholdtsen That is a great goal, but how about you go through those patches, decide which ones are appropriate for this repo (some may be Debian specific) and raise PRs for the ones that are relevant?

**Comment by petterreinholdtsen** [comment]
[Erik de Castro Lopo]
> @petterreinholdtsen That is a great goal, but how about you go through
> those patches, decide which ones are appropriate for this repo (some
> may be Debian specific) and raise PRs for the ones that are relevant?

Thank you for the feedback.  I just wanted to bring those patches into
the light, to see how interested the xiph group were in looking at them.
I do not know the flac code base nor these patches enough to be able to
figure out which ones are appropriate for this repo.

I notice from the patch file names there are mostly memory leaks and
privacy issues addressed, but that is about it. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by erikd** [comment]
The memory leak fixes are commits pulled from this repo (I am the author in the patch Author field) and the privacy leaks are mostly about conforming to Debian standards.

The former are obviously not relevant and the later may be. I will have a look.

**Comment by erikd** [comment]
I have had a look at the privacy leak patches and while I can see why they are relevant for Debian, I do not think they are appropriate for FLAC, mainly because these are are actual HTML pages that get uploaded to the FLAC documentation site and the content being removed in those patches are parfectly valid for the FLAC documentaiton site.

**Comment by petterreinholdtsen** [comment]
[Erik de Castro Lopo]
> I have had a look at the privacy leak patches and while I can see why
> they are relevant for Debian, I do not think they are appropriate for
> FLAC, mainly because these are are actual HTML pages that get uploaded
> to the FLAC documentation site and the content being removed in those
> patches are parfectly valid for the FLAC documentaiton site.

Right.  Does this mean you have a data processing agreement with the
companies receving information about the readers of the FLAC
documentation?  Is the agreement public so I can have a look at it?

Personally, I would prefer it if reading the documentation would not ask
my browser to send information about my reading to third parties, but as
far as I understand the legal framework at least according to GDPR, it
might be OK if a good data processing agreement is in place.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by erikd** [comment]
There is no agreement.

I have just checked and since many web browsers no longer provide a referr header, the validation no longer works. That means its ok to remove these links. However, we still need to validate the HTML

I am going to try `tidy` (from Debian) as a standalone command line HTML validator.

**Comment by orbea** [comment]
I personally have been hoping a new release would be made sometime before Slackware 15 so that a release with commit https://github.com/xiph/flac/commit/5dff53c0cc3f8969b6a1d608ce6a4d120d78efce could be included, but I am biased. :)

**Comment by rillian** [comment]
> I looked at `w3c-markup-validaton` but is has the most crazy list of dependencies (it installs `apache` FFS).

It's probably installing the entire validation service, which of course requires a web server to provide to interface. It looks like the validator is a [perl cgi wrapper](https://github.com/w3c/markup-validator/blob/master/httpd/cgi-bin/check) around a [perl module](https://metacpan.org/pod/Bundle::W3C::Validator) around libxml.

Since it's xhtml, one may use the [xmllint](http://xmlsoft.org/xmllint.html) from the libxml package. `xmllint --valid --noout *.html` passed the documents for me, although I had to install the `xhtml1-dtds` package first; fetching resources over the network gave a stack of undeclared element and entity errors.

**Comment by orbea** [comment]
Seems `1.3.3` is out now so this issue is effectively resolved?

https://git.xiph.org/?p=flac.git;a=commit;h=f764434a39e8a8715d5871bb263189e5a7298280

**Comment by erikd** [comment]
Well 1.3.3 is out, but i borked the release, so I intend to do a 1.3.4 release as soon as I can.

**Comment by jherby2k** [comment]
> Well 1.3.3 is out, but i borked the release, so I intend to do a 1.3.4 release as soon as I can.

Out of curiosity, what's borked? Should we be avoiding 1.3.3?

**Comment by rillian** [comment]
The CMake build has the wrong version number. If you build with autotools (`./configure && make`) it should be safe to use.

**Comment by erikd** [comment]
As @rillian says, it was just the version number in the CMake build system and a couple of other really minor issues. Will be making a 1.3.4 release as soon as I find some time.

**Comment by Barough** [comment]
> @Barough "All these years"? Really? The last release was 2.5 years ago. Let me remind you that before I became the maintainer, FLAC had no new release for 5 or 6 years.
> 
> What has gone into the code base since then that you are so desperate for that using a git checkout for is inadequate?

Sry about that. Didn't ment 2 upset ya. I could have said things in a different way.

There was some 'security' related fixes if i recall correctly that was fixed rather quick after v1.3.2 was released. It's these type of fixes that i really think warrent a new release asap. 
Then it would also be nice to see a new release being pushed out after a year or so with the fixes and improvments from the Git.

Now i said my stuff.

**Comment by erikd** [comment]
> There was some 'security' related fixes if i recall correctly that was fixed rather quick after v1.3.2 was released. It's these type of fixes that i really think warrent a new release asap.

Which issue?

**Comment by erikd** [comment]
1.3.3 was released over a month ago. Closing this.

**Comment by gabor-zoka** [comment]
Here is a major head-ache for me:

https://github.com/xiph/flac/commit/5f5035d2093421c43770eb0f0628e2f60aea61a5

flac -t fails on this for 6 months now. Arch Linux and probably many others do not apply the patch (despite me giving the exact patch to the build script, because the maintainers do not have the time). 

But I know they pick up new release relatively quickly.

Before you ignore this. My 3000 CD collection chokes on this on 5 tracks. What's the point of the integrity check if it does not work.

I am patching and building my own now from github, but I really do not understand why such a big deal to cut a release, and why we have to go through this pain.

Gábor
