### ISSUE TITLE
get_client_data_from_decoder()

### ISSUE THREAD

**Issue by sezero** [xiph/flac#121]
Commit a0027fadfa8 adds a new function get_client_data_from_decoder()
which is marked as FLAC_API, but not in public stream_decoder.h and in
protected/stream_decoder.h instead.  Also, the function isn't prefixed
by FLAC_ either.

Any specific reason for these?

**Comment by erikd** [comment]
:man_shrugging: I don't use Windows. I expect the community to provide *all* needed Windows related fixes.

**Comment by sezero** [comment]
> I don't use Windows. I expect the community to provide _all_ needed Windows related fixes.

This one has nothing to do with windows

**Comment by erikd** [comment]
This was probably not vetted closely enough when it was added. I remember sitting on it for a while because I wasn't sure if it was a good idea, but I actually don't remember merging it.

Now that I look at it again, I do not think this function is a good idea. If we are to keep it, the function should probably be called something like `flac_decoder_client_data`, and should return `const void*` rather than `void*` to document the fact that what it points to should not be messed with. The Doxygen comments should also be updated to give a use case (eg the one from the PR) and a warning not to mess with the memory pointed to by the pointer.

I wonder if its not possible to solve this problem in another neater way.

@ChristopD

**Comment by sezero** [comment]
> > I don't use Windows. I expect the community to provide _all_ needed Windows related fixes.
> 
> This one has nothing to do with windows

As is evidenced by https://github.com/xiph/flac/pull/47, btw..

**Comment by ChristopD** [comment]
Hello,

Before adding this pull request, we tried all other way for java/JNA implementation, but we always lost hand on existing data in all cases.
That's the most difference with C implementations.

We're open minded about the name and the way to declare this function. As pure java developpers, we could have miss something with your best practices.
But we unfortunatly can not have a new week of dev. and tests to make it works with another way, almost two years after this development.

I hope you can keep this function, even renamed, avoiding us to make a custom patch for each new release.

Best Regards
ChristopD

**Comment by erikd** [comment]
https://github.com/xiph/flac/pull/124
