### ISSUE TITLE
How to calculate bit rate of a FLAC file using libFLAC (that is, C)?

### ISSUE THREAD

**Issue by mrkkrp** [xiph/flac#18]
Hello, I'm not sure this is a correct place to ask this sort of question, but since `flac-dev` mailing list doesn't seem to be too active, I decided I would try here.

My question is regarding calculation of bit rate. In order to calculate bit rate we need to divide total size of compressed audio data by its duration in seconds. Duration in seconds can be calculated from sample rate and total number of samples, both values come from stream info metadata block and I have no problem with reading those. However, I don't see how I can get total size of audio data using libFLAC. So far I've read only the section about metadata, but stream encoder/decoder modules do not seem to provide a way to get this information either.

What is the correct way to get total size of audio data?

**Comment by erikd** [comment]
Oh wow, a fellow Haskell hacker. I'm a megaparsec user :)

Anyway to try to answer your question. Firstly libFLAC does not provide any direct way of getting the actual size of the audio data. It could probably be done, but probably only using the FLAC internals. However, when calculating the data rate of an compressed audio file, it is normal to include the metadata size overhead  in the size calculation because that would be what coming over the wire if you were streaming the data over a TCP connection.

**Comment by mrkkrp** [comment]
Thanks a lot, I'll just get file size then and divide it by number of seconds :-)

**Comment by erikd** [comment]
That's how everyone else does it.
