### ISSUE TITLE
Add support for DSF and DFF audio data compression

### ISSUE THREAD

**Issue by audiomuze** [xiph/flac#187]
Given FLAC is the de facto standard for lossless audio it'd be a real boon to add compression support for DSF and DFF audio streams also, enabling users to retain all the benefits of FLAC for these audio streams.

**Comment by erikd** [comment]
This will not happen. FLAC is about FLAC and converting to and from a couple of the most common uncompressed formats like WAV and AIFF.

The appropriate place for things like DSF and DFF is https://github.com/erikd/libsndfile which is specifically designed to read and write multiple formats (including FLAC by the way).

**Comment by ValZapod** [comment]
What HE obviously meant here is a way to store very high smple rate DSD stuff (2.8224 MHz, for example and more). https://en.m.wikipedia.org/wiki/Direct_Stream_Digital

I suppose that is impossible... 1.048575MHz is max after https://github.com/xiph/flac/pull/219/files?

**Comment by ktmf01** [comment]
It's not just the samplerate, the problem is also that FLACs algorithm is not suited for DSD. It was designed for [PCM](https://en.wikipedia.org/wiki/Pulse-code_modulation) audio, but DSD is [PDM](https://en.wikipedia.org/wiki/Pulse-density_modulation) audio. In other words, it works fine with 8-bit and 16-bit audio for example, but it's LPC prediction will never properly work with 1-bit streams, which is what DSD is. Storing DXD on the other hand (which is a PCM precursor to DSD meant for studio environments) would probably work fine
