### ISSUE TITLE
flac -t claims MD5 signature unset in STREAMINFO, yet it is present?

### ISSUE THREAD

**Issue by smopucilowski** [xiph/flac#192]
I've been hitting this issue and I can't seem to pin down the cause:

```
$ flac -t 07*.flac

flac 1.3.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

07 - Natur - Flying.flac: WARNING, cannot check MD5 signature since it was unset in the STREAMINFO
ok
$ metaflac --list --block-type=STREAMINFO 07*.flac
METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4096 samples
  maximum blocksize: 4096 samples
  minimum framesize: 2031 bytes
  maximum framesize: 12721 bytes
  sample_rate: 44100 Hz
  channels: 2
  bits-per-sample: 16
  total samples: 16639640
  MD5 signature: 009e8d8af89cf3d98f748aa9383f9e90
```

Running checks it seems to appear in about one in two hundred files. It is present in `flac v1.3.{1,2}`.

**Comment by smopucilowski** [comment]
Possibly related to issue #155. Re-enconding the file over itself does not clear the issue.

**Comment by fspoettel** [comment]
Running into the same issue as well, similar number of files affected. Reencoding does not fix the issue. Can provide sample files if that helps with debugging.

**Comment by BezPowell** [comment]
Also experiencing this on Fedora 32 with flac 1.3.3.

**Comment by pastif** [comment]
I'm having the same issue. It seems to only happen when files have two zeros at the start of the MD5 signature.

**Comment by smopucilowski** [comment]
A `--enable-debug` build doesn't appear to trip the error.

**Comment by pastif** [comment]
I built and installed flac 1.3.0 in a clean Arch Linux container and the same error happened. I installed flac 1.3.1 from the repos in an Ubuntu xenial container and couldn't reproduce the error. This is getting a bit beyond me, but I guess the bug is caused by something that changed in gcc or glibc. The memcmp call at line 1310 of src/flac/decode.c seems to be the trigger. I found this issue on the gcc bug tracker but don't understand it enough to know if it's actually the cause.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189

I tried building 1.3.3 on Arch with the optimization flag set to -O1 and that does appear to fix the issue (gcc 10.1.0-2 and glibc 2.31-5).

**Comment by smopucilowski** [comment]
When flac returns `WARNING, cannot check MD5 signature since it was unset in the STREAMINFO` on a file, `--warnings-as-errors` does not convert the warning to an error and exits with return code `0`.

**Comment by pastif** [comment]
I just noticed there's a patch for this on the Sourceforge bug tracker. It does fix the issue for me.

https://sourceforge.net/p/flac/bugs/478/

Is GitHub now the preferred place to report issues? The Xiph website still links to Sourceforge but I noticed someone there being told to reopen an issue here.
