### ISSUE TITLE
seek errors

### ISSUE THREAD

**Issue by kiilerix** [xiph/flac#276]
I have problems with a file in Ardour ( https://tracker.ardour.org/view.php?id=8863 ) and think I tracked it down to reproduce in xiph flac on git master, using a small hack to trigger a special position in the presumably correctly written test program:
```diff
--- a/src/test_seeking/main.c
+++ b/src/test_seeking/main.c
@@ -328,6 +328,10 @@ static FLAC__bool seek_barrage(FLAC__bool is_ogg, const char *filename, FLAC__of
        for (i = 0; !stop_signal_ && (count == 0 || i < count); i++) {
                FLAC__uint64 pos;
 
+               if (1) {
+                       pos = count;
+                       i = count;
+               } else
                /* for the first 10, seek to the first 10 samples */
                if (n >= 10 && i < 10) {
                        pos = i;
```

Testing a special case with a 160 MB flac file generated by Soundcraft Ui24R, currently available on 
https://wetransfer.com/downloads/1eadb1aa46ba40b0e301f745ee4b782120220120202728/5db0efc9546315e640f764b310cca39c20220120202728/dea7f9 :
```
$ src/test_seeking/test_seeking 12\ ORGAN\ R.flac 90059776

+++ seek test: FLAC__StreamDecoder (native FLAC, read_mode=0)

CPU info (x86-64):
  CMOV ....... Y
  MMX ........ Y
  SSE ........ Y
  SSE2 ....... Y
  SSE3 ....... Y
  SSSE3 ...... Y
  SSE41 ...... Y
  SSE42 ...... Y
  AVX ........ Y
  FMA ........ n
  AVX2 ....... n
  AVX OS sup . Y
stream decoder state is FLAC__STREAM_DECODER_END_OF_STREAM
file's total_samples is 123578720
Begin seek barrage, count=90059776
#90059776:seek(90059776)... FAILED, FLAC__stream_decoder_seek_absolute() FAILED, state = 6 (FLAC__STREAM_DECODER_SEEK_ERROR)
```
but for positions a bit before or after, it works fine:
```
$ src/test_seeking/test_seeking 12\ ORGAN\ R.flac 90059770

+++ seek test: FLAC__StreamDecoder (native FLAC, read_mode=0)

CPU info (x86-64):
  CMOV ....... Y
  MMX ........ Y
  SSE ........ Y
  SSE2 ....... Y
  SSE3 ....... Y
  SSSE3 ...... Y
  SSE41 ...... Y
  SSE42 ...... Y
  AVX ........ Y
  FMA ........ n
  AVX2 ....... n
  AVX OS sup . Y
stream decoder state is FLAC__STREAM_DECODER_END_OF_STREAM
file's total_samples is 123578720
Begin seek barrage, count=90059770
#90059770:seek(90059770)... frame@90059770(134)... OK

PASSED!
...
```
and same for
```
$ src/test_seeking/test_seeking 12\ ORGAN\ R.flac 90059779
```

I guess this file happens to hit some bad corner case in the complex bisection code in `seek_to_absolute_sample_`?

This is on Fedora 35.

**Comment by ktmf01** [comment]
Many thanks for providing such a clear example! I did some research and found out the problem is that the decoder finds a valid looking frame that isn't actually valid at all, and this badly messes up the seeking process. As it so happens, this is caused by what I think is a 20-year old mistake (see #274) I stumbled upon last week. Very happy coincidence indeed.

We cannot completely eliminate these seeking errors sadly, but it is possible to make them less likely to happen. I think it is already extremely rare, but I will propose a fix as implied in #274 that will make this 2^16 times less likely to happen.

**Comment by kiilerix** [comment]
Agreed. In my example, in the 3rd bisection iteration in `seek_to_absolute_sample_`, we search to 112980393 and find an invalid sample 8064. This gives a very unbalanced bisection, and we only realize the inconsistency after 272 iterations where we fail.

I agree that frames that fail CRC should fail (!), and that the bisection algorithm shouldn't accept sync on such invalid frames but  should skip such failures and keep searching. Still, it seems unfortunate to assume that CRC collisions doesn't happen; they are "rare", but not "unlikely", as for example a sha1 check would be.

As extra safety, we could change the algorithm to always read 2 frames when sync'ing after a seek. That would make it even more unlikely to succeed on an out-of-sync position.

(Ideally, we should only go `FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC` after a seek, but it seems like the spec allows any amount of noise between any frames?)

**Comment by ktmf01** [comment]
> I agree that frames that fail CRC should fail (!), and that the bisection algorithm shouldn't accept sync on such invalid frames but should skip such failures and keep searching. Still, it seems unfortunate to assume that CRC collisions doesn't happen; they are "rare", but not "unlikely", as for example a sha1 check would be.

Yes, but the CRC is not the only thing that is being checked. Without validating the CRC this problem is already very rare.

> As extra safety, we could change the algorithm to always read 2 frames when sync'ing after a seek. That would make it even more unlikely to succeed on an out-of-sync position.

Combined with checking whether the frame numbers are consecutive, that would indeed push the odds of this happening. However, seeking would presumably become twice as slow. It is also possible to just check whether the next frame header has a current frame number + 1 (or current sample number + blocksize), that would be a lot faster than a full decode. It makes the seeking code a lot more complex though, and debugging seeking problems is usually already quite troublesome.

I'll try fixing this specific seeking problem in a second way, by adding more sanity checks to the seeking code. Currently, the upper and lower bounds are updated without checking whether the new bounds are possible at all. I think that adds quite a lot of safety, with as little extra (complex) code as possible

> (Ideally, we should only go `FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC` after a seek, but it seems like the spec allows any amount of noise between any frames?)

No, the spec doesn't allow anything inbetween frames. Why would going to FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC be beneficial?

**Comment by kiilerix** [comment]
> > (Ideally, we should only go `FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC` after a seek, but it seems like the spec allows any amount of noise between any frames?)
> 
> No, the spec doesn't allow anything inbetween frames. As far as I know the decoder only goes to FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC on seeking or an error. Where do you see it doing that otherwise?

`read_frame_` ends with
```
        decoder->protected_->state = FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC;
        return true;
```
so two consequtive calls to `FLAC__stream_decoder_process_single` would do `frame_sync_` in-between and quietly skip garbage. `FLAC__stream_decoder_process_until_end_of_stream` will also pass through `frame_sync_` between each frame.


Anyway, my real world problem seems to be solved nicely with the fix you hinted at:
```diff
--- a/src/libFLAC/stream_decoder.c
+++ b/src/libFLAC/stream_decoder.c
@@ -2129,13 +2129,10 @@ FLAC__bool read_frame_(FLAC__StreamDecoder *decoder, FLAC__bool *got_a_frame, FL
        }
        else {
-               /* Bad frame, emit error and zero the output signal */
+               /* Bad frame, emit error and fail similarly to bad zero padding above */
                send_error_to_client_(decoder, FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH);
-               if(do_full_decode) {
-                       for(channel = 0; channel < decoder->private_->frame.header.channels; channel++) {
-                               memset(decoder->private_->output[channel], 0, sizeof(FLAC__int32) * decoder->private_->frame.header.blocksize);
-                       }
-               }
+               decoder->protected_->state = FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC;
+               return true;
        }
 
        *got_a_frame = true;
```

I will try that out with Ardour, and look forward to see your fix ;-)

**Comment by ktmf01** [comment]
I tried to evaluate how rare this problem is. I used test_seeking without your patch on the problem file to establish how many random seeks are needed to find the problem. Your file has 123 million samples and after running test_seeking 10 times, I found that the worst of the 10 cases needed 8 million random seeks to find the problem. That would mean doing a number of random seeks 10% of the total number of samples should suffice to find such a problem.

I ran over 50 hours such tests on various files, running 2 billion random seeks on files with together 20 billion (stereo) samples, and I haven't found a second example yet. 20 billion samples with a samplerate of 44100Hz equals 126 hours of content. If the CRC check is enabled and the odds increase by 2^16, this translates to no problem found in 8 million hours of content, and even then, the user must be unlucky enough to seek to the exact right point in that 8 million hours of content to trigger it.

That seems rare enough to me.

**Comment by wader** [comment]
@ktmf01 Hey, i'm struggle with a similar issues with ffmpeg:s flac parser which always uses sync finding heuristics to chunk up the bitstream into packets. I've fixed a few a them but here is probably the most extreme one, might be a good test case for you https://trac.ffmpeg.org/ticket/9621

**Comment by ktmf01** [comment]
Indeed it seems that sample also breaks seeking with #277 

I'll take a look at it.

**Comment by ValZapod** [comment]
FFmpeg patch to fix https://trac.ffmpeg.org/ticket/9621 

https://patchwork.ffmpeg.org/project/ffmpeg/patch/CAPYw7P40pW-TtapFEpakovXUhCCC5h0WOwfBq06Xv5ghd3UE3A@mail.gmail.com/

FYI.
