### ISSUE TITLE
8/16 bits in 24-bit WAVE producing noise. And <25 bits in 32-bit WAVE

### ISSUE THREAD

**Issue by H2Swine** [xiph/flac#301]
Attachment contains two "questionable but WavPack approved" WAVE files and three "written afresh by WavPack, should be valid" WAVE files.  And the .wv used to generate the latter.

Files M1F1-int24-AFsp_bits17to24areZero.hexeditedto08validbits.wav and M1F1-int24-AFsp_bits17to24areZero.hexeditedto16validbits :
I took a 24 bit test file (with the least significant 8 bits being zero), hexedited it to 8 or 16 valid bits.  flac.exe interprets as 8-bit WAVE or 16-bit WAVE and outputs noise.
WavPack thinks they are OK.  (Note, WavPack zeroes out the remaining bits.)
Expected behaviour would be to reject the 8-bits (because bits 9-16 are not zero) and process the 16 bits-in-24 into something that sounds like the WavPack file does.

M1F1-int24-AFsp_bits17to24areZero.hexeditedto08validbits_wavpack-ir.wv and M1F1-int24-AFsp_bits17to24areZero.hexeditedto16validbits_wavpack-ir.wv were created with WavPack with the -ir option: then wvunpack will write WAVE headers anew. 
Thus, the .wav files that end with "wavpack-ir.wav" have freshly written WAVE container, so even if my WAVE-incompetent hex-editing led to something questionable, _these fresh ones should be valid_. 
flac.exe treats them the same as the above.

Also: 
I did a bunch of this - https://hydrogenaud.io/index.php?topic=121447.msg1008257#msg1008257 has most (though not the wavpack -ir).
It sometimes happens that flac.exe writes 0 bytes files (why?) and 9 KB header-only files.  If it is unhappy about the signal, should it then output anything at all? 
(And flac.exe also rejects 24 bits in 32-bit container.  Kinda fair enough to reject 32 when you don't support 32, even if it is 24.)

Attachment:
[b-bits-in-C-container-wave_with_wv.zip](https://github.com/xiph/flac/files/8190392/b-bits-in-C-container-wave_with_wv.zip)

**Comment by ValZapod** [comment]
> should it then output anything at all?

This is normal to write small files, because writing a file [touching it to a filesystem] is very slow compared to actually encoding. FFmpeg does it, ts files are actually wrtten with 0 bytes, but mp4 are written header first. This is correct behaviour.

>Kinda fair enough to reject 32 when you don't support 32, even if it is 24

You should never write 24 bits in 32 but container, this is not TrueHD that allows for 16 its in 24 bits container, because there is no any metadata!! Also ffmpeg support pure 32 bit (and 64 bit soon to be added, wav 64 bits already works) decoding and encoding after @ktmf01 patch here: 

There is still a bug in ffmpeg that forbids it for merging. https://patchwork.ffmpeg.org/project/ffmpeg/patch/20220108142437.756529-1-mvanb1@gmail.com/

**Comment by ValZapod** [comment]
> WAVE and AIFF have that, and FLAC has that.

TrueHD does not have that. There is no way to know whether it has all 24 bits set before decoding.

>In the very least it could have left it as a temp file.

And then you need to move (from /tmp) and rename the file. It is also slow. Or rename only, that is what Chrome does, .crdownload file.

**Comment by ktmf01** [comment]
Here is another [Wave File Specification](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Docs/multichaudP.pdf)

> Ambiguity within WAVE_FORMAT_PCM
It is important to enumerate the assumptions made by WAVE_FORMAT_PCM. One
assumption is that the nBlockAlign field contains exactly one set of samples (one block).
Also, each sample must be byte-aligned within the block. The byte-aligned space that each
sample consumes is called the sample's "container." **Additionally, there cannot be any
extra space between the end of the last sample container and the actual end of the block.**
In other words, nBlockAlign must be an integer multiple of nChannels, and that multiple
is considered the "container size" for the sample.
>
> Although it was not necessarily the original intent, some entities treat wBitsPerSample as
equivalent to the container size. In other words, the number of bits of valid data was
assumed equal to the size of the container. This assumption held well for 8-bit and 16-bit
audio. With the coming of high fidelity audio equipment for render and capture, 20-bit and
24-bit streams emerged. Specifying the actual bit resolution of the samples in a byte-
aligned stream became important; the accepted interpretation of wBitsPerSample started
to unravel, because its value is not rigidly enforced by all software. In many cases, it
continued to be the container size. In other cases, however, the field was used to indicate
the bits of actual valid data, while the container size was inferred from nBlockAlign and
nChannels (an example would be wBitsPerSample = 20, nBlockAlign = 8, nChannels
= 2).
>
>It was not considered feasible to resolve this issue either way without causing many legacy
problems for WAVE_FORMAT_PCM, so the new formats include an additional field that
clarifies this ambiguity. The new formats are intended to handle those cases in which the
actual bits of precision are not equal to the container size, as well as all cases in which the
container size is greater than sixteen bits.

As I read it, there is a lot of ambiguity in the format. To assure that `flac` operates losslessly, I think it is best to let `flac` refuse to process these files.

**Comment by ValZapod** [comment]
What does ffmpeg do? This? 
https://github.com/FFmpeg/FFmpeg/blob/e71d5156c8fec67a7198a0032262036ae7d46bcd/libavformat/wavdec.c#L770

**Comment by ktmf01** [comment]
I don't know what ffmpeg does exactly, but the result is quite similar to what `flac` makes of it, it decodes to a noisy screech.

**Comment by ktmf01** [comment]
The WavPack encoder can create a file that is playable by ffmpeg for example

**Comment by ValZapod** [comment]
> The WavPack encoder can create a file that is playable by ffmpeg for example

I meant wav files, not wv or flac. Who can play those correctly?

**Comment by ktmf01** [comment]
The WavPack encoder can *encode* these wav files to a wv file that can be played correctly by ffmpeg.

**Comment by ktmf01** [comment]
Are we talking about the same thing?

I tried playing M1F1-int24-AFsp_bits17to24areZero.hexeditedto08validbits.wav in the zip file added to the first message of this issue.

Playing that file directly with ffplay, Windows Media Player or foobar2000 results in screech-like sound.

Converting the file with `wavpack` to a .wv file and playing **that** file in ffplay results in hearing two voices.

Converting the file with `flac` to a .flac file and playing **that** file in ffplay results in similar screech-like sound.

Do you get different results using ffplay?

**Comment by ValZapod** [comment]
> Do you get different results using ffplay?

I only tested M1F1-int24-AFsp_bits17to24areZero.wavpack-ir.wav, that one does work correctly. Should have tested all of them, others are bad indeed. Well, if ffmpeg cannot do it, the files are probably invalid or too niche.

**Comment by H2Swine** [comment]
As i pointed out in the thread mentioned in the initial post ( https://hydrogenaud.io/index.php?topic=121447 ), there is an issue for 8 valid bits, so 8 in 24 behaves different from 16 in 24. 
- Since 8 bit is unsigned, that means "8-or-less in 16/24/32" is potentially ill-behaved and - since at least _some part of the specification_ can be read so as the container size should be the next multiple of 8: safest thing is to reject those? 
     - I'd say, either behave like WavPack or reject?
     - But 9 in 16 is valid and 9 in 24 isn't dangerous?
- With some kind of 32-bit support about to come, and it is the 32nd bit that is the problem (as mid/side could lead to sum/difference signals taking 33 bits), there is no reason to rule out 31 bits in 32-bit container, nor 25-bit in 32-bit container - they could be processed left+right, mid+side, left+side or right+side, no problem? 
     - 9 to 24 in 32 isn't dangerous either?

So if C is container size and b is valid number of bits, one needs to check if b is between 4 (that limitation still stands?) and C inclusive, and then one has to choose whether a check that b>C-8 should be performed after an IF b<9? And the following would work: 
- If b>C, reject ELSE
- check that b>3 if that still stands, ELSE
- if b<9 then check that C = 8 (reject otherwise) 
... and then process, taking into account that if b=C=32, then dual-mono.

**Comment by ktmf01** [comment]
Turns out this was fixed once. Original bug report: https://sourceforge.net/p/flac/bugs/79/
Original fix: https://github.com/xiph/flac/commit/94f81b0a9a2c421702315df79c6e0d4a4425412b
Broke with this reorganisation: https://github.com/xiph/flac/commit/13c63e4fff7e9291106058540b296475ed03b449
Last remnant removed here: https://github.com/xiph/flac/commit/8bbbf56403808ff75126cd0840a936aedbc4113b
