### ISSUE TITLE
Support CMAKE

### ISSUE THREAD

**Issue by mancoast** [xiph/flac#43]
CMAKE enables easy cross-compilation.

**Comment by cristianadam** [comment]
Visual Studio has official CMake support in VS2017.  For previous versions of Visual Studio CMake can generate Visual Studio project files.

In the meantime vcpkg (the Microsoft open source package manager for Visual Studio) has a CMake port for libflac. See https://github.com/Microsoft/vcpkg/blob/master/ports/libflac/CMakeLists.txt

**Comment by erikd** [comment]
If Cmake support is added, can the current Visual Studio build system be removed?

**Comment by mancoast** [comment]
In my opinion, cmake is optimal for platform agnostic build system. The cmake file is used to generate fresh visual studio project files during the compilation process, so it does deprecate the current msvc files

**Comment by erikd** [comment]
I prefer autotools myself, but if someone is willing to contribute a CMake build system that does everything that the current autotools build system does, I'll be happy to add it.

**Comment by IanLilleyT** [comment]
+1 for cmake support

I'm building ogg, vorbis, and flac for linux, mac, and windows from source inside a build script, and having to mess around with flac's visual studio solution is pretty frustrating compared to the other audio libs which support cmake. In addition, I had trouble using autotools on linux and mac so I opted to use Makefile.lite, where I had to manually change the ogg include and libs dirs. A lot of manual patching in my script.

Unfortunately I don't know cmake or the flac internals well enough to add a cmake build system, but I wanted to share my experience.

**Comment by erikd** [comment]
>  I had trouble using autotools on linux and mac

What problems? Autotools is the official build tool for FLAC on Linux and Mac. If you have an issue, report it. Obviously, when you you do, you will need to provide Linux version and autotool versions.

**Comment by IanLilleyT** [comment]
I'm pretty sure I'm just doing something wrong. My main frustration is with windows, and that's where something like cmake would have the biggest benefit.

**Comment by erikd** [comment]
> I'm pretty sure I'm just doing something wrong with autotools.

Well since autotools is the official way of doing things, we should figure out what is going on. At least on Linux is should be as simple as:

    ./autogen.sh
    ./confgiure
    make all check

**Comment by IanLilleyT** [comment]
My original description was super misleading, sorry. I've only compiled on mac and windows so far. I lumped linux in because I assumed it would be the same process/issue as mac. Anyway, I found out the output went to `src/libFLAC/.libs/` instead of `objs/release/lib` (where I expected). The build output and readme aren't really clear about this. I was originally using finder to search for the generated libs and nothing came up because they were in a hidden folder. Also a nitpick from someone completely unfamiliar with autotools, the readme would be easier to follow if the initial command under the GNU environment section in the readme was simply: `./autogen.sh && ./configure && make`. I didn't know to call `autogen.sh` until getting to the end of the section.

Your silence on the rest of my comment makes it seem like you have no interest in adding cmake, I don't blame you, but I think it would be good for the project and consistent with some of the other audio libs. Maybe someone else will have interest in doing it. In the meantime I will use my hacky workarounds for windows. Glad to have figured out the mac issue though, so thanks for the help.

Here are my versions (from homebrew):
```
autoconf 2.69
automake 1.16.1_1
libtool 2.4.6_1
flac 1.3.2_1
libogg 1.3.3
libvorbis 1.3.6
nasm 2.14.02
```
Full build output: https://pastebin.com/raw/36SQkZuk

**Comment by erikd** [comment]
> Also a nitpick from someone completely unfamiliar with autotools,

Patches accepted.

> Your silence on the rest of my comment makes it seem like you have no interest in adding cmake

I actually think CMake is a very poor configuration tool. AFAIAC, it only has a single advantage over autotools, the ability to generate Visual Studio project files. Since I don't think its a good tool I have neither the motivation nor the expertise to get it working.

**Comment by krokoziabla** [comment]
@erikd Probably can be closed now
