### ISSUE TITLE
Why some antivirus treat libflac as a virsus

### ISSUE THREAD

**Issue by yixinuestc** [xiph/flac#441]
Hello,everyone:
     I use flac 1,3,3 version in the programe.But some antivirus  treat it as a virsus(Win32.hack.Undef). Does anyone know,why.Thanks in advance.

**Comment by ktmf01** [comment]
Where did you get those executables? Perhaps best to ask there?

**Comment by sagamusix** [comment]
Also, virus detection has never been an exact science. A lot of heuristics are involved that *very* frequently mis-identify legitimate software as viruses. It is extremely common that at least one out of the ~70 products on virustotal.com identify a program as a virus. Usually it's some random antivirus vendor you have never heard of, which on its own should already be a telltale sign that it's a false positive.

You can submit the executable to your antivirus vendor as a false positive sample so that they can finetune their signature database for the next signature update.

**Comment by dicru** [comment]
Some antivirus consider any unsigned exe or dll as a virus.

**Comment by ktmf01** [comment]
@yixinuestc Can I close this issue?
