### ISSUE TITLE
Improve documentation for removing an interface.

### ISSUE THREAD

**Issue by razed11** [xiph/flac#45]
I've read the notes for embedded developers:

> Unused parts may be pruned by some simple editing of src/libFLAC/Makefile.am

It's not clear to me how to remove the metadata interface. I tried commenting some source files and then running automake:

```
	#metadata_iterators.c \
	#metadata_object.c \
```
When I build I get linker errors. Linux calls that I don't want/need as I am running on an RTOS:

```
metadata_iterators.c:(.text+0x52c): undefined reference to `chmod'
metadata_iterators.c:(.text+0x534): undefined reference to `utime'
metadata_iterators.c:(.text+0x540): undefined reference to `chown'
metadata_iterators.c:(.text+0x552): undefined reference to `chown'
```

My goal is only to encode data that will be pushed to the cloud.

**Comment by erikd** [comment]
Does it build on your RTOS with those file included?

**Comment by erikd** [comment]
The lines you quote were added to the README by the original author Josh Coalson in 2007. The original author has had no involvement with this project since 2009. Since that part of the document is so old and not incorrect, the only "improvement" I can see that is worth making is removal of that section.

**Comment by razed11** [comment]
I think what was written in terms of dependencies is correct. This is more of an autoconf/automake thing (a tool I've learned to build this library). When I commented those files in `Makefile.am`, ran automake, then configure, they were still built and I got the errors. Do I need to run `autogen.sh`? 

I can cross compile much of the library except the part that make these system calls. Until I have the library I can't link. My guess is that the low level encoder portions of the code are portable to my platform it's just a question of will the performance meet my needs. If I could get some support I wouldn't mind writing up something. I suspect others might be interested.

**Comment by razed11** [comment]
My approach above is flawed. I can't simply remove those two `metadata_` files as they contain code that is referenced by `encode.c` among other things.

**Comment by erikd** [comment]
Like I say, the last time what you are hoping to achieve was suspected to work was 2007.

**Comment by ktmf01** [comment]
@razed11 Are you still interested in a answer to this question? Seeing that it is always 5 years since the last reply, can I close this issue?

I just tried to remove the metadata interface and the stream encoder, and compilation of libFLAC went just fine actually. I removed bitwriter.c. cpu.c, fixed_intrin_sse2.c, fixed_intrin_ssse3.c, lpc_intrin_sse2.c, lpc_intrin_sse41.c, lpc_intrin_avx2.c, lpc_intrin_avx2.c, lpc_intrin_vsx.c, lpc_intrin_neon.c, metadata_iterators.c, metadata_object.c, stream_encoder.c, stream_encoder_intrin_sse2.c, stream_encoder_intrin_ssse3.c, stream_encoder_intrin_avx2.c and window.c and ran ` ./autogen.sh && ./configure && make` on a clean git checkout. Compilation of libFLAC went just fine. Compilation of `flac` didn't of course, because it depends on these removed parts of the library.

I think that is were the problem was, it seems you were expecting to build a `flac` command line program without any metadata handling, but this is not facilitated. It is also not was the README says. It says libFLAC can be built without an encoder and metadata interface.  libFLAC is used in embedded applications for playback of FLAC files, and the possibility to build libFLAC with just a decoder seems to work fine.
