### ISSUE TITLE
Error: Corrupted FLAC; stream Error: MD5 mismatch

### ISSUE THREAD

**Issue by deroverda** [xiph/flac#632]
Hi guys. I have a track that plays perfectly but analyzing the track in the latest foobar 2.0 along with trader's little helper I get errors. Normally the error would get fixed/disappear if I re-encode the file back to flac or sometimes decode to wav and the to flac again. But this time nothing works. Here's the flac error report: 

```
flac 1.4.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2023  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

07 - See Me Through,Burning Ground.flac: *** Got error code 2:FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
*** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC


07 - See Me Through,Burning Ground.flac: ERROR while decoding data
                                         state = FLAC__STREAM_DECODER_ABORTED
```
                                         
Here's the corrupted flac if anyone wants to give it a go. 
DL: [download](https://files.catbox.moe/kvvrac.flac)

PS. this is a live recording captured by an audience recorder. in other words, this is not copyrighted audio.

**Comment by ktmf01** [comment]
Please be more specific about what didn't work. What did you try, specifically? It seems you've tried more than you're letting on, because the title says md5 mismatch, but that is not in the command output?

**Comment by deroverda** [comment]
I tried several things. 

1. ffmpeg -i "the flac" -c copy fix.flac (this didn't work since the flac has errors) 
2. trader's little helper (tried decoding and encoding, none of these options worked)
3. i tried flac.exe decode and encode. nothing worked.

**Comment by deroverda** [comment]
> Please be more specific about what didn't work. What did you try, specifically? It seems you've tried more than you're letting on, because the title says md5 mismatch, but that is not in the command output?

maybe you can give the track a try and tell me what you did if you manage to get it error-free.

**Comment by ktmf01** [comment]
There is no way to get this to decode error free, because the file has an error. There is no arguing with that.

However, you can 'salvage' the file with `flac -dF`. In the resulting decode, the block with the error (a little more than 0.1s) will be muted.

**Comment by deroverda** [comment]
thanks for testing the file. may I ask, since the track plays fine, in what way is it negative/bad having this errored track? since I can't see/hear that the track is faulty, why would I really bother to try to fix/mask it? In other words, in what way is this track damaged?

**Comment by ktmf01** [comment]
You might not care that not difference can be heard, but FLAC is a lossless codec. Many people do care, that's why they use FLAC.

I can't say how the track is damaged. I can only say the CRC doesn't validate. There is no telling what went wrong or what is wrong with the audio.

**Comment by H2Swine** [comment]
@deroverda : flac.exe is not very verbose about precisely _where_ the error is. That could be a wishlist item, of course, to report in more detail where the first error is and how many samples are affected.
This file is OK until neary 11min11sec, and it seems to me there is only one broken frame: 0.1045 seconds (because this file has frames of 4608 samples each - nowadays encoders typically choose a 4096 samples length). 
Reference FLAC will - in the more recent versions, at least - react by muting the entire frame if it is corrupted. Safest choice. The thing is that, typically, everything is wrong from first corruption to end of frame (this is because previous samples are used to calculate the next samples, so past errors make future garbage) - but first corruption could be first frame or frame 1234 or whatever, there is no way to tell precisely where. (Technically speaking, there are scenarios where you can know that sample 1234 is so wrong that the error must have occurred already, but nothing says anything was right about sample 1233.)

You typically don't want to re-encode. That will only wrap the glitch into a file that is technically OK but contains corrupted audio. Something is wrong, and you rather want to be warned that it is. Just accept that you are missing a tenth of a second.

(How it happened? Best guess would be someone downloaded it with a p2p client and aborted it just before the final bits were transferred.)

**Comment by ValeZAA** [comment]
>How it happened? Best guess would be someone downloaded it with a p2p client and aborted it just before the final bits were transferred.

That is not how it works. First of all Bittorrent has 2 MiB or smaller segments. Second of all, the not downloaded segment will be zeroed out and even marked as sparse in the filesystem.
